# -*- coding: utf-8 -*-
"""MostrarIndicesHorizontal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Psychohistorian11/BitBusters/blob/master/Taller_1/MostrarIndicesHorizontal.ipynb
"""

def mostrarIndices(n, m): # O(n^2)
    for i in range(n):  # O(n)
        if i % 2 == 0:
            for j in range(m):    # O(n^2)
                print(f"[{i}][{j}]")   # O(n^2)
        else:
            for j in range(m-1, -1, -1): # O(n^2)
                print(f"[{i}][{j}]")  # O(n^2)

mostrarIndices(5,3) # O(n^2)

# Ecuacion: O(n^2)

