# -*- coding: utf-8 -*-
"""ZigZagHorizontalyBigO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19gythF4g1zvywr5Tdgc4GShT5RiB8kRm
"""

def zig_zag(filas,columnas,inicio = 0,recorrido = []): #O(n^2)

  while inicio < filas: # O(n)

    if ((inicio % 2) == 0): # O(n)
      for i in range(columnas): #O(n^2)
        recorrido.append(f"[{inicio},{i}]")#O(n^2)
      inicio += 1 # O(n)
    else: # O(n)
      for i in range((columnas-1),-1,-1): #O(n^2)
        recorrido.append(f"[{inicio},{i}]") #O(n^2)
      inicio +=1 #O(n)
  return recorrido #O(1)

def imprimir_zig_zag(filas,columnas): #O(n^2)

  recorrido = zig_zag(filas,columnas) #O(n^2)

  for i in recorrido: #O(n)
    print(i, end =",") #O(n)

filas = int(input("Ingrese el número de filas: ")) # O(1)
columnas = int(input("Ingrese el número de columnas")) #O(2)
imprimir_zig_zag(filas, columnas) #O(n^2)

# Ecuación: 2 O(1) + O(n^2)